#ifndef Celeste_AST_NODE_deamerreserved_star__deamerreserved_or__index_access__deamerreserved_or__anonymous_access__deamerreserved_or__function_access__auto_deduce_array_________H
#define Celeste_AST_NODE_deamerreserved_star__deamerreserved_or__index_access__deamerreserved_or__anonymous_access__deamerreserved_or__function_access__auto_deduce_array_________H

#include "Celeste/Ast/Node/Celeste.h"
#include <Deamer/External/Cpp/Ast/Node.h>

namespace Celeste { namespace ast { namespace node { 

	class deamerreserved_star__deamerreserved_or__index_access__deamerreserved_or__anonymous_access__deamerreserved_or__function_access__auto_deduce_array________ : public Celeste<deamerreserved_star__deamerreserved_or__index_access__deamerreserved_or__anonymous_access__deamerreserved_or__function_access__auto_deduce_array________>
	{
	private:
	public:
		deamerreserved_star__deamerreserved_or__index_access__deamerreserved_or__anonymous_access__deamerreserved_or__function_access__auto_deduce_array________(deamer::external::cpp::ast::NodeInformation information_, std::vector<deamer::external::cpp::ast::Node*> nodes_)
		: Celeste<deamerreserved_star__deamerreserved_or__index_access__deamerreserved_or__anonymous_access__deamerreserved_or__function_access__auto_deduce_array________>(information_, nodes_, {})
		{
		}
	};

}}}

#endif // Celeste_AST_NODE_deamerreserved_star__deamerreserved_or__index_access__deamerreserved_or__anonymous_access__deamerreserved_or__function_access__auto_deduce_array_________H
